export const profileQuery = {
  'data': {
    'getSession': {
      'profile': {
        'id': '37faf0df-4164-4fab-b80f-5e1b9957b411',
        'firstName': 'Victor',
        'lastName': 'Hugo',
        'email': 'minidog@mailinator.com',
        'document': '45325123440',
        'phone': '+5511983768051',
      },
    },
  },
}

export const orderGroupQuery = {
  'data': {
    'orderGroup': [
      {
        'orderId': '884610097279-01',
        'orderGroup': '884610097279',
        'state': 'approve-payment',
        'creationDate': '2018-12-19T13:01:46.1217018Z',
        'items': [
          {
            'uniqueId': '18986263B72D42F48D72349C30F0C86D',
            'id': '30',
            'productId': '17',
            'name': 'PRODUTO RNB - 20,00 nos SC 1 e 2 PRODUTO 4',
            'skuName': 'PRODUTO 4',
            'tax': 0,
            'price': 2000,
            'listPrice': 2000,
            'sellingPrice': 2000,
            'quantity': 4,
            'seller': '1',
            'imageUrl': 'http://recorrenciaqa.vteximg.com.br/arquivos/ids/155410-55-55/mambo.png?v=636093678270100000',
            'detailUrl': '/abobora-em-calda-bom-principio-350g/p',
          },
          {
            'uniqueId': '5F3A383A5EF74FBE8C6171B55FD88295',
            'id': '2',
            'productId': '2',
            'name': 'Produto Variação SKU Variação 1 Azul',
            'skuName': 'SKU Variação 1 Azul',
            'tax': 0,
            'price': 10000,
            'listPrice': 10000,
            'sellingPrice': 10000,
            'quantity': 1,
            'seller': '1',
            'imageUrl': 'http://recorrenciaqa.vteximg.com.br/arquivos/ids/155387-55-55/bola.png?v=635917503224200000',
            'detailUrl': '/produto-variacao/p',
          },
          {
            'uniqueId': 'ADEAE577E80C43CCB24BA0D056252AE4',
            'id': '21',
            'productId': '9',
            'name': 'areia de gato',
            'skuName': 'areia de gato',
            'tax': 0,
            'price': 1600,
            'listPrice': 1438,
            'sellingPrice': 1600,
            'quantity': 3,
            'seller': '1',
            'imageUrl': 'http://recorrenciaqa.vteximg.com.br/arquivos/ids/155395-55-55/areia-de-gato.jpg?v=635974405759000000',
            'detailUrl': '/areiadegato/p',
          },
          {
            'uniqueId': '26733EF499DE4CF68452FE8AD000A4A9',
            'id': '18',
            'productId': '6',
            'name': 'Ração para peixe',
            'skuName': 'Ração para peixe',
            'tax': 0,
            'price': 100,
            'listPrice': 200,
            'sellingPrice': 100,
            'quantity': 2,
            'seller': '1',
            'imageUrl': 'http://recorrenciaqa.vteximg.com.br/arquivos/ids/155392-55-55/AlconKOI.jpg?v=635918402228600000',
            'detailUrl': '/racaoparapeixe/p',
          },
        ],
        'shippingData': {
          'logisticsInfo': [
            {
              'itemIndex': 0,
              'shippingEstimate': null,
              'shippingEstimateDate': null,
              'selectedSla': 'PAC',
              'deliveryChannel': null,
              'slas': [
                {
                  'id': 'PAC',
                  'name': 'PAC',
                  'price': 0,
                  'shippingEstimate': '4bd',
                  'deliveryWindow': null,
                  'deliveryChannel': 'delivery',
                  'pickupStoreInfo': {
                    'additionalInfo': null,
                    'address': null,
                    'dockId': null,
                    'friendlyName': null,
                    'isPickupStore': false,
                  },
                },
                {
                  'id': 'Normal',
                  'name': 'Normal',
                  'price': 5,
                  'shippingEstimate': '3bd',
                  'deliveryWindow': null,
                  'deliveryChannel': 'delivery',
                  'pickupStoreInfo': {
                    'additionalInfo': null,
                    'address': null,
                    'dockId': null,
                    'friendlyName': null,
                    'isPickupStore': false,
                  },
                },
              ],
              'deliveryIds': null,
            },
            {
              'itemIndex': 1,
              'shippingEstimate': null,
              'shippingEstimateDate': null,
              'selectedSla': 'PAC',
              'deliveryChannel': null,
              'slas': [
                {
                  'id': 'PAC',
                  'name': 'PAC',
                  'price': 0,
                  'shippingEstimate': '4bd',
                  'deliveryWindow': null,
                  'deliveryChannel': 'delivery',
                  'pickupStoreInfo': {
                    'additionalInfo': null,
                    'address': null,
                    'dockId': null,
                    'friendlyName': null,
                    'isPickupStore': false,
                  },
                },
                {
                  'id': 'Normal',
                  'name': 'Normal',
                  'price': 118,
                  'shippingEstimate': '3bd',
                  'deliveryWindow': null,
                  'deliveryChannel': 'delivery',
                  'pickupStoreInfo': {
                    'additionalInfo': null,
                    'address': null,
                    'dockId': null,
                    'friendlyName': null,
                    'isPickupStore': false,
                  },
                },
              ],
              'deliveryIds': null,
            },
            {
              'itemIndex': 2,
              'shippingEstimate': null,
              'shippingEstimateDate': null,
              'selectedSla': 'PAC',
              'deliveryChannel': null,
              'slas': [
                {
                  'id': 'PAC',
                  'name': 'PAC',
                  'price': 0,
                  'shippingEstimate': '4bd',
                  'deliveryWindow': null,
                  'deliveryChannel': 'delivery',
                  'pickupStoreInfo': {
                    'additionalInfo': null,
                    'address': null,
                    'dockId': null,
                    'friendlyName': null,
                    'isPickupStore': false,
                  },
                },
                {
                  'id': 'Normal',
                  'name': 'Normal',
                  'price': 353,
                  'shippingEstimate': '3bd',
                  'deliveryWindow': null,
                  'deliveryChannel': 'delivery',
                  'pickupStoreInfo': {
                    'additionalInfo': null,
                    'address': null,
                    'dockId': null,
                    'friendlyName': null,
                    'isPickupStore': false,
                  },
                },
              ],
              'deliveryIds': null,
            },
            {
              'itemIndex': 3,
              'shippingEstimate': null,
              'shippingEstimateDate': null,
              'selectedSla': 'PAC',
              'deliveryChannel': null,
              'slas': [
                {
                  'id': 'PAC',
                  'name': 'PAC',
                  'price': 0,
                  'shippingEstimate': '4bd',
                  'deliveryWindow': null,
                  'deliveryChannel': 'delivery',
                  'pickupStoreInfo': {
                    'additionalInfo': null,
                    'address': null,
                    'dockId': null,
                    'friendlyName': null,
                    'isPickupStore': false,
                  },
                },
                {
                  'id': 'Normal',
                  'name': 'Normal',
                  'price': 24,
                  'shippingEstimate': '3bd',
                  'deliveryWindow': null,
                  'deliveryChannel': 'delivery',
                  'pickupStoreInfo': {
                    'additionalInfo': null,
                    'address': null,
                    'dockId': null,
                    'friendlyName': null,
                    'isPickupStore': false,
                  },
                },
              ],
              'deliveryIds': null,
            },
          ],
          'address': {
            'addressId': 'bcff3e538b0b488483b73f0e036ebb4e',
            'addressType': 'residential',
            'receiverName': 'Victor Hugo',
            'city': 'São Paulo',
            'state': 'SP',
            'street': 'Rua Domiciano Leite Ribeiro',
            'number': '18',
            'neighborhood': 'Vila Guarani (Z Sul)',
            'complement': null,
            'country': 'BRA',
          },
          'selectedAddresses': [
            {
              'addressId': 'bcff3e538b0b488483b73f0e036ebb4e',
              'addressType': 'residential',
              'receiverName': 'Victor Hugo',
              'city': 'São Paulo',
              'state': 'SP',
              'street': 'Rua Domiciano Leite Ribeiro',
              'number': '18',
              'neighborhood': 'Vila Guarani (Z Sul)',
              'complement': null,
            },
          ],
        },
        'packageAttachment': null,
        'paymentData': {
          'transactions': [
            {
              'transactionId': 'C32BE35C11D5483FB62E6F7BCF3230C2',
              'payments': [
                {
                  'paymentSystemName': 'Visa',
                  'paymentSystem': '2',
                  'lastDigits': '2324',
                  'group': 'creditCard',
                },
              ],
            },
          ],
        },
        'value': 23000,
        'storePreferencesData': {
          'currencyCode': 'BRL',
          'countryCode': 'BRA',
        },
      },
    ],
  },
}
