export const profileQuery = {
  'profile': {
    'id': '37faf0df-4164-4fab-b80f-5e1b9957b411',
    'firstName': 'Victor',
    'lastName': 'Hugo',
    'email': 'victor2142@gmail.com',
    'document': '45325123440',
    'phone': '+5511983768051',
  },
}

export const orderGroupQuery = {
  'orderGroup': [
    {
      'orderId': '884912046760-01',
      'state': 'payment-approved',
      'creationDate': '2018-12-20T18:34:19.8386354Z',
      'items': [
        {
          'uniqueId': '8C7B18D6EFEB487D84CDCC52B8AC0272',
          'id': '37',
          'productId': '24',
          'name': 'PRODUTO 11',
          'skuName': 'PRODUTO 11',
          'tax': 0,
          'price': 1000,
          'listPrice': 1000,
          'sellingPrice': 1000,
          'quantity': 3,
          'seller': '1',
          'imageUrl': 'http://recorrenciaqa.vteximg.com.br/arquivos/ids/155417-55-55/mambo.png?v=636093678308170000',
          'detailUrl': '/acafrao-estigmas-carmencita-caixa-04g/p',
        },
        {
          'uniqueId': '5FEBB52526D84E149E4CF24BDBBCA862',
          'id': '29',
          'productId': '16',
          'name': 'PRODUTO RNB - SC 1: 15.00 / SC 25,00: PRODUTO 3',
          'skuName': 'PRODUTO 3',
          'tax': 0,
          'price': 1500,
          'listPrice': 1500,
          'sellingPrice': 1500,
          'quantity': 2,
          'seller': '1',
          'imageUrl': 'http://recorrenciaqa.vteximg.com.br/arquivos/ids/155409-55-55/mambo.png?v=636093678266030000',
          'detailUrl': '/abacaxi-em-caldas-vega-400g/p',
        },
        {
          'uniqueId': '93CA25E6097442BF9F6A82BD22C198A4',
          'id': '39',
          'productId': '26',
          'name': 'PRODUTO 13',
          'skuName': 'PRODUTO 13',
          'tax': 0,
          'price': 1000,
          'listPrice': 1000,
          'sellingPrice': 1000,
          'quantity': 3,
          'seller': '1',
          'imageUrl': 'http://recorrenciaqa.vteximg.com.br/arquivos/ids/155419-55-55/mambo.png?v=636093678331400000',
          'detailUrl': '/aceto-balsamico-carbonell-250ml/p',
        },
        {
          'uniqueId': 'EED6EDD02D83433BA6F82BB62BF956BC',
          'id': '48',
          'productId': '35',
          'name': 'PRODUTO 22',
          'skuName': 'PRODUTO 22',
          'tax': 0,
          'price': 1000,
          'listPrice': 1000,
          'sellingPrice': 1000,
          'quantity': 2,
          'seller': '1',
          'imageUrl': 'http://recorrenciaqa.vteximg.com.br/arquivos/ids/155428-55-55/mambo.png?v=636093678395600000',
          'detailUrl': '/achocolatado-actigen-nescau-2-0-lata-400g/p',
        },
        {
          'uniqueId': '173EEBE80C5948888BB71F4827DDBF29',
          'id': '34',
          'productId': '21',
          'name': 'PRODUTO 8',
          'skuName': 'PRODUTO 8',
          'tax': 0,
          'price': 1000,
          'listPrice': 1000,
          'sellingPrice': 1000,
          'quantity': 1,
          'seller': '1',
          'imageUrl': 'http://recorrenciaqa.vteximg.com.br/arquivos/ids/155414-55-55/mambo.png?v=636093678290400000',
          'detailUrl': '/acafrao-cerroni-villa-pote-190g/p',
        },
      ],
      'shippingData': {
        'logisticsInfo': [
          {
            'itemIndex': 0,
            'shippingEstimate': null,
            'shippingEstimateDate': null,
            'selectedSla': 'PAC',
            'slas': [
              {
                'id': 'PAC',
                'name': 'PAC',
                'price': 0,
                'shippingEstimate': '4bd',
                'deliveryWindow': null,
                'deliveryChannel': 'delivery',
              },
              {
                'id': 'Normal',
                'name': 'Normal',
                'price': 136,
                'shippingEstimate': '3bd',
                'deliveryWindow': null,
                'deliveryChannel': 'delivery',
              },
            ],
            'deliveryIds': null,
          },
          {
            'itemIndex': 1,
            'shippingEstimate': null,
            'shippingEstimateDate': null,
            'selectedSla': 'PAC',
            'slas': [
              {
                'id': 'PAC',
                'name': 'PAC',
                'price': 0,
                'shippingEstimate': '4bd',
                'deliveryWindow': null,
                'deliveryChannel': 'delivery',
              },
              {
                'id': 'Normal',
                'name': 'Normal',
                'price': 91,
                'shippingEstimate': '3bd',
                'deliveryWindow': null,
                'deliveryChannel': 'delivery',
              },
            ],
            'deliveryIds': null,
          },
          {
            'itemIndex': 2,
            'shippingEstimate': null,
            'shippingEstimateDate': null,
            'selectedSla': 'PAC',
            'slas': [
              {
                'id': 'PAC',
                'name': 'PAC',
                'price': 0,
                'shippingEstimate': '4bd',
                'deliveryWindow': null,
                'deliveryChannel': 'delivery',
              },
              {
                'id': 'Normal',
                'name': 'Normal',
                'price': 136,
                'shippingEstimate': '3bd',
                'deliveryWindow': null,
                'deliveryChannel': 'delivery',
              },
            ],
            'deliveryIds': null,
          },
          {
            'itemIndex': 3,
            'shippingEstimate': null,
            'shippingEstimateDate': null,
            'selectedSla': 'PAC',
            'slas': [
              {
                'id': 'PAC',
                'name': 'PAC',
                'price': 0,
                'shippingEstimate': '4bd',
                'deliveryWindow': null,
                'deliveryChannel': 'delivery',
              },
              {
                'id': 'Normal',
                'name': 'Normal',
                'price': 91,
                'shippingEstimate': '3bd',
                'deliveryWindow': null,
                'deliveryChannel': 'delivery',
              },
            ],
            'deliveryIds': null,
          },
          {
            'itemIndex': 4,
            'shippingEstimate': null,
            'shippingEstimateDate': null,
            'selectedSla': 'PAC',
            'slas': [
              {
                'id': 'PAC',
                'name': 'PAC',
                'price': 0,
                'shippingEstimate': '4bd',
                'deliveryWindow': null,
                'deliveryChannel': 'delivery',
              },
              {
                'id': 'Normal',
                'name': 'Normal',
                'price': 46,
                'shippingEstimate': '3bd',
                'deliveryWindow': null,
                'deliveryChannel': 'delivery',
              },
            ],
            'deliveryIds': null,
          },
        ],
        'address': {
          'addressId': '120535803747684',
          'addressType': 'residential',
          'receiverName': 'Victor Hugo',
          'city': 'São Paulo',
          'state': 'SP',
          'street': 'Rua Domiciano Leite Ribeiro',
          'number': '18',
          'neighborhood': 'Vila Guarani (Z Sul)',
          'complement': null,
        },
      },
      'packageAttachment': null,
      'paymentData': {
        'transactions': [
          {
            'transactionId': '82126A968EC54778A49DE672104F518A',
            'payments': [
              {
                'paymentSystemName': 'Visa',
                'paymentSystem': '2',
                'value': 12000,
                'installments': 1,
                'lastDigits': '2324',
                'group': 'creditCard',
              },
              {
                'paymentSystemName': 'Visa',
                'paymentSystem': '2',
                'value': 12000,
                'installments': 1,
                'lastDigits': '2324',
                'group': 'creditCard',
              },
            ],
          },
        ],
      },
      'value': 12000,
      'storePreferencesData': {
        'currencyCode': 'BRL',
      },
    },
  ],
}
